theme: jekyll-theme-slate
#theme: jekyll-theme-minimal

title: "MakeitPing.Cloud - Hands-on networking workshop on AWS"

description: "Learn with hands-on networking workshops on AWS with makeitping.cloud"

author: Antonio Feijao UK

page.author: AntonioFeijaoUK

logo: "https://avatars1.githubusercontent.com/u/2548084?s=460&u=9e50289e33b8c3fd3d8778afd89f46d27ec70f35&v=4"

permalink: pretty

show_downloads: "false"

google_analytics: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
  - jemoji
  - jekyll-avatar
  - jekyll-paginate
# - jekyll-redirect-from

markdown: kramdown

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
 parse_block_html: true
 
